### ISSUE TITLE
parser.tab.hh not found

### ISSUE THREAD

**Issue by Neo-Oli** [bqv/weechat-xmpp#2]
Hi

I am trying to compile this and I am currently stuck at this error:
`./sexp/scanner.hh:7:10: fatal error: 'parser.tab.hh' file not found`

Is this file provided by some unlisted dependency?
I also get the same error about `location.hh`

**Comment by bqv** [comment]
My guess is you don't have bison or flex installed. I'll add a note to add that to the readme, it's not obvious in fairness...

Also if I remember correctly, where I left this is a bit funky right now. Checkout afedd306 instead of HEAD, or maybe even the r1 tag. I'll start hacking on this again soon :)

**Comment by bqv** [comment]
pretty sure this was fixed
