### ISSUE TITLE
/help xmpp show no commands available

### ISSUE THREAD

**Issue by emdee-is** [bqv/weechat-xmpp#5]
```
11:35  weechat     | 
11:35  weechat     | [xmpp]  /xmpp
11:35  weechat     | 
11:35  weechat     | get xmpp plugin version
```

And no commands complete of ```/xmpp```

**Comment by bqv** [comment]
Have you ever used weechat before?
Try /help, look under the [xmpp] block, there's all the commands that this uses. Help on any of those is descriptive enough

Maybe your confusion is based on the fact that most other scripts and plugins try and hide all their stuff under one big command - This does not, because it's trying to be a first-class protocol plugin.
Will amend the /xmpp help to make that more obvious
